#include "debug.h"
#include "general.h"
#include "io.h"
#include "handlers.h"
#include "keyboard.h"
#include "pic.h"
#include "video.h"

void enable_interrupts() {
    __asm__ volatile ("sti");
}

void disable_interrupts() {
    __asm__ volatile ("cli");
}

// Wanted layout: [ Reserved/exceptions | Software | PIC ]
// because it is easier to distinguish software interrupts 
// from ones generated by PIC
void interrupt_handler(struct stack_frame* sf) {
    int16_t irq = sf->n - master_PIC_first_input_IDT_position;
    if (irq < 0) {
        if (sf->n < 32) { // is reserved
            printf("Reserved interrupt ");
        } else {
            printf("Software interrupt ");
        }
        printf("%d happened with errcode %d\n", sf->n, sf->errcode);
    } else {
        if (irq == 0) {
            static int steps = 0;
            if (!steps--) {
                steps += PIT_interrupt_div;
                printf("Tick\n");
            }
        // } else if (irq == 1) {
        //     printf("Keyboard interrupt %d happened on irq %d with errcode %d\n",
        //            sf->n, irq, sf->errcode);
        //     video_printf("%x ", get_scancode()); 
        //     // currently disabled until I find more info
        } else {
            printf("Hardware interrupt %d happened on irq %d with errcode %d\n",
                   sf->n, irq, sf->errcode);
        }
        send_EOI_PIC(irq);
    }
}